--- 

- hosts: test
  become: true
  tasks:

  - name: append to test.txt
    tags: always
    ansible.builtin.lineinfile:
      path: /home/bill/test.txt      
      insertafter: EOF
      line: 'testing 1...2...3...'