--- 

- hosts: media_containers
  become: true
  tasks:

  - name: update repo cache
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: create group media
    tags: always
    ansible.builtin.group:
      name: media
      state: present
      gid: 1776

  - name: create group docs 
    tags: always
    ansible.builtin.group:
      name: docs
      state: present
      gid: 1787

  - name: create bill user
    tags: always
    user: 
      name: bill
      groups: root,sudo,media,docs

  - name: create hal user
    tags: always
    user: 
      name: hal
      groups: sudo,media,docs

  - name: add ssh key for bill
    tags: always
    authorized_key: 
      user: bill
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkdzXCp480fWqPU0pMP4BLtrSEG/V399GAXr+Y4ZTVK bill"

  - name: add ssh key for hal
    tags: always
    authorized_key: 
      user: hal
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgyiZ4tMW4B6bJ6VNep4e9grqu0Mc8JbDoZsFs3Kd1EYPKMt/p2oS0nH8BeqVgYVZ34AW4Yw42DSYza1upJ7vOOwN0YpjkXoXhW9B9u5caS9IfRjSa4nVCX3eXRY6XpMWfX25BxTZNxI8BT8QihIhX7MDFSO4d/93YcBwnhXenLIe1Mf5Od1B7qbr2j7V4w2VLt1UeRrhrlPnYFawhdm0kllGNL9oFaU0QEvjaect3wBVKVybhDUGIeo5r3Gkt6SctYc69XlJyufWI6eEfptP19rPhTMJzP4W3gIKqNcs/XeiuUeUoWkpLC8Od4DUcl1+VbbIAIX/yjj4MVHk48Uvhpvp3VZ2EcDxLTxV4M6ZQTsTno40w880CJ3uqLFDycjdvBhw1JNQZ4VCLAKi6i3JeH3Gvo8M1a9QNMBbk7/g1qm3mZ3NWLaTltXdnrr/X+/sCVUNWdEaH7fektUMWTl/YtqeivPr4nHDnaJseKxkRwjmemX02YZDS/i++12WwW4c= bill@semaphore"
 
  - name: add sudoers file for hal
    tags: always
    copy:
      src: /etc/sudoers.d/hal
      dest: /etc/sudoers.d/hal
      owner: root
      group: root
      mode: 0440

  - name: add sudoers file for bill
    tags: always
    copy:
      src: /etc/sudoers.d/bill
      dest: /etc/sudoers.d/bill
      owner: root
      group: root
      mode: 0440

  - name: Recursively change ownership of hal's home directory
    ansible.builtin.file:
      path: /home/hal
      state: directory
      recurse: yes
      owner: hal
      group: hal

  - name: Recursively change ownership of bill's home directory
    ansible.builtin.file:
      path: /home/bill
      state: directory
      recurse: yes
      owner: bill
      group: bill

  - name: Set timezone to America/New_York
    community.general.timezone:
      name: America/New_York

  - name: add packages
    ansible.builtin.apt:
      pkg:
      - nfs-common

  - name: create media directory
    ansible.builtin.file:
      path: /mnt/media
      state: directory
      mode: '0775'
      owner: bill
      group: media
  
  - name: mount media volume
    ansible.posix.mount:
      src: 192.168.86.90/media
      path: /mnt/media
      opts: rw,vers=3.0,uid=1000,gid=1000
      state: mounted
      fstype: nfs