---

- name: create proxmox container
  hosts: proxmox

  Tasks:
  community.general.proxmox:
    api_user: root@pam
    api_password: Jackson0317!
    api_host: pve
    password: Jackson0317!
    hostname: test1
    ostemplate: 'local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
    disk: 'local-lvm:20'
    cores: 2
    timezone: host
    memory: 2048
    unorivileged: false


# api token id root@pam!semaphore
# api secret 65702452-82b5-46f3-ac95-b12f6f5ab485
