---

- hosts: pve_only
  become: true
  tasks:
  
  - name: create proxmox container
    community.general.proxmox:
      api_user: root@pam
      api_password: Jackson0317!
      api_host: pve
      node: pve
      password: Jackson0317!
      hostname: test1
      onboot: yes
      ostemplate: 'local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
      disk: 'local-lvm:20'
      cores: 2
      memory: 2048
      swap: 2048
      unprivileged: false
      netif:
        net0: "name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"
    - name: Execute ip a
      ansible.builtin.command: /usr/bin/perl -T /usr/sbin/pct exec {{created_vmid}} ip a show dev eth0
      register: ip_output
    - name: Get IP
        set_fact:
          created_ip: "{{ ip_output | regex_search('inet (\\d*\\.\\d*\\.\\d*\\.\\d*)/', '\\1')

# api token id root@pam!semaphore
# api secret 65702452-82b5-46f3-ac95-b12f6f5ab485
