---

- hosts: all 
  become: true 
  tasks:

  - name: create group media
    tags: always
    ansible.builtin.group:
      name: media
      state: present
      gid: 1776

  - name: create group docs 
    tags: always
    ansible.builtin.group:
      name: docs
      state: present
      gid: 1787

  - name: create bill user
    tags: always
    user: 
      name: bill
      groups: bill,adm,root,sudo,media,docs

  - name: add ssh key for bill
    tags: always
    authorized_key: 
      user: bill
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkdzXCp480fWqPU0pMP4BLtrSEG/V399GAXr+Y4ZTVK bill"

  - name: add sudoers file for bill
    tags: always
    copy:
      src: /etc/sudoers.d/bill
      dest: /etc/sudoers.d/bill
      owner: root
      group: root
      mode: 0440
