---

- hosts: new_machines
  become: true
  tasks:

  - name: update repo cache
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: add packages
    ansible.builtin.apt:
      pkg:
      - git
      - nfs-common
      - software-properties-common
      - mc
      - cmatrix

  - name: add smd cred file for bill
    tags: always
    copy:
      src: /home/bill/.SMBcredentials
      dest: /home/bill/.SMBcredentials
      owner: bill
      group: bill
      mode: 0644

  - name: Install VS Code
    community.general.snap:
      name: code
      classic: true 

  - name: Set timezone to America/New_York
    community.general.timezone:
      name: America/New_York

  - name: mount download directory
    ansible.posix.mount:
      src: 192.168.86.90:/mnt/ssd-files/home/bill/Desktop
      path: /home/bill/Desktop
      opts: rw,sync
      state: mounted
      fstype: nfs


  
