---

- hosts: new
  become: true
  pre_tasks:

  - name: update repo cache
    tags: always
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]  

- hosts: new
  become: true
  roles:
    - base

- hosts: new
  become: true
  roles:
    - workstations

- hosts: new
  become: true
  roles:
    - lxc

- hosts: new
  become: true
  roles:
    - media_h

- hosts: new
  become: true
  roles: 
    - media_p

- hosts: new
  become: true
  roles:
    - docs  

- hosts: localhost 
  connection: local 
  become: true 
  roles: 
    - workstations
  

#  - name: fetch remote public key
#    community.crypto.openssl_publickey_info:
#      path: /home/bill/.ssh/bill
#    register: bill_ssh

 # - name: append new key to authorized file
 #   ansible.builtin.lineinfile: 
 #     path: /home/bill/test/test_auth_file
 #     insertafter: EOF
 #     line: bill_ssh

  

  

  
    
  

