---

- hosts: containers
  become: true
  tasks:

  - name: update repo cache
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: create bill user
    tags: always
    user: 
      name: bill
      password: $6$YKsZbl1tRGp7V22w$hPkvWuJCgktUhaXOAWcRKl8Ouk4z8LXSD0tQBRvApWAEf82xGvxpHjuL6rjKB.1eB5aNSBXnVXNIDWrbFtFeg1
      groups: root,sudo,media,docs

  - name: add ssh key for bill
    tags: always
    authorized_key: 
      user: bill
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkdzXCp480fWqPU0pMP4BLtrSEG/V399GAXr+Y4ZTVK bill"

  - name: add sudoers file for bill
    tags: always
    copy:
      src: /etc/sudoers.d/bill
      dest: /etc/sudoers.d/bill
      owner: root
      group: root
      mode: 0440

  - name: Recursively change ownership of bill's home directory
    ansible.builtin.file:
      path: /home/bill
      state: directory
      recurse: yes
      owner: bill
      group: bill

  - name: Set timezone to America/New_York
    community.general.timezone:
      name: America/New_York