---

- hosts: test
  become: true
  tasks:

  - name: update repo cache
    tags: always
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]  

   

  

#  - name: fetch remote public key
#    community.crypto.openssl_publickey_info:
#      path: /home/bill/.ssh/bill
#    register: bill_ssh

 # - name: append new key to authorized file
 #   ansible.builtin.lineinfile: 
 #     path: /home/bill/test/test_auth_file
 #     insertafter: EOF
 #     line: bill_ssh

  

  

  
    
  

