--- 

- hosts: test
  become: true
  tasks:
  
  - name: Generate an OpenSSH keypair for Bill
    tags: workstations
    community.crypto.openssh_keypair:
      path: /home/bill/.ssh/bill
      type: ed25519
      owner: bill
      group: bill
      regenerate: never
      comment: "bill {{ ansible_facts['nodename'] }} "

  - name: copy and register bill.pub
    ansible.builtin.shell: 
      cmd: cat /home/bill/.ssh/bill.pub      
    register: pub_key

  - debug:
      msg: "{{pub_key.stdout}}"
      
  - name:
    set_fact:
      key: "{{pub_key.stdout}}"

  - name: create host_vars file
    ansible.builtin.lineinfile:     
      path: /home/bill/semaphore/host_vars/{{ansible_hostname}}.yml
      line: pub_key:{{key}}
      owner: bill
      group: bill
      mode: '0644'
      create: yes
    delegate_to: localhost

- hosts: ssh  
  become: true
  tasks:

  - name: Display public key
    debug:
      msg: "The public key is: {{ lookup('file', '/home/bill/semaphore/host_vars/' + ansible_facts['nodename'] + '.yml')['pub_key'] }}"
    when: "'new' in group_names"
        
  - name: Set pub_key fact for each server
    set_fact:
      key: "{{ pub_key }}"
    when: pub_key is defined

  - debug:
      msg: "{{key}}" 
  
  - name: Copy public key to all hosts
    ansible.builtin.lineinfile:
      path: /home/bill/.ssh/authorized_keys      
      insertafter: EOF
      line: "{{key}}"