--- 

- hosts: test
  become: true
  vars:
    pub_key: "{{ lookup('file', '/home/bill/.ssh/bill.pub') }}"
  tasks:

  - name: Generate an OpenSSH keypair for Bill
    tags: workstations
    community.crypto.openssh_keypair:
      path: /home/bill/.ssh/bill
      type: ed25519
      owner: bill
      group: bill
      regenerate: never
      comment: "bill {{ ansible_facts['nodename'] }} "

  - name: copy and register bill.pub
    ansible.builtin.shell: cat /home/bill/.ssh/bill.pub      
    register: pub_key

- hosts: ssh
  become: true
  tasks:

  - name: Copy public key to all hosts
    ansible.builtin.lineinfile:
      path: /home/bill/.ssh/authorized_keys      
      insertafter: EOF
      line: {{ hostvars['test'].pub_key }}
  