--- 

- hosts: test
  become: true
  tasks:

  - name: Generate an OpenSSH keypair for Bill
    tags: workstations
    community.crypto.openssh_keypair:
      path: /home/bill/.ssh/bill
      type: ed25519
      owner: bill
      group: bill
      regenerate: never
      comment: "bill {{ ansible_facts['nodename'] }} "

  - name: copy and register bill.pub
    ansible.builtin.shell: 
      cmd: cat /home/bill/.ssh/bill.pub      
    register: pub_key

  - debug:
      msg: "{{pub_key.stdout}}"

  - name: make pub_key fact to pass to next play
    set_fact:
      pub_key: "{{pub_key}}"

- hosts: ssh
  gather_facts: no
  become: true
  tasks:

  - name: set pub_key fact to distribute to servers
    set_fact: 
      key: "{{ groupvars['test']['pub_key'] }}"
  
  - name: Copy public key to all hosts
    ansible.builtin.lineinfile:
      path: /home/bill/.ssh/authorized_keys      
      insertafter: EOF
      line: "{{key}}"