- name: create user bill
  tags: lxc
  user:
    name: bill
    password: $6$YKsZbl1tRGp7V22w$hPkvWuJCgktUhaXOAWcRKl8Ouk4z8LXSD0tQBRvApWAEf82xGvxpHjuL6rjKB.1eB5aNSBXnVXNIDWrbFtFeg1
    groups: sudo
    shell: /bin/bash
    uid: 1000

- name: Set timezone to America/New_York
  tags: lxc
  community.general.timezone:
    name: America/New_York

